name: Test

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: llvm-tools-preview
        override: true
    - uses: actions-rs/cargo@v1.0.3
      with:
        command: check

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: llvm-tools-preview
        override: true
    - uses: actions-rs/cargo@v1.0.3
      with:
        command: test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, llvm-tools-preview
        override: true
    - uses: actions-rs/cargo@v1.0.3
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: clippy, llvm-tools-preview
        override: true
    - uses: actions-rs/cargo@v1.0.3
      with:
        command: clippy
        args: -- -Dwarnings

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: '-Zinstrument-coverage'
      RUSTDOCFLAGS: '-Zinstrument-coverage'
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: nightly
        components: llvm-tools-preview
        override: true
    - uses: actions-rs/cargo@v1.0.3
      with:
        command: build
    - uses: actions-rs/cargo@v1.0.3
      env:
        LLVM_PROFILE_FILE: 'grcov-%p-%m.profraw'
      with:
        command: test
    - name: grcov
      run: ./target/debug/grcov --branch --binary-path ./target/debug/ --source-dir . --output-type lcov --output-path lcov.info --ignore-not-existing --ignore "/*" .
    - uses: codecov/codecov-action@v2.0.2
      with:
        files: ./lcov.info
